language: d
sudo: false

addons:
  apt:
    update: true
    packages:
      - autoconf
      - automake
      - curl
      - g++
      - libtool
      - make
      - unzip

script:
  - dub build
  - dub test
  - dub build :protoc-gen-d
  - cd conformance && ./run-conformance-test.sh
