language: d
sudo: false

script:
  - dub build
  - dub test
  - dub build :protoc-gen-d
  - cd $TRAVIS_BUILD_DIR/conformance && ./run-conformance-test.sh
  - cd $TRAVIS_BUILD_DIR/examples && PATH=$TRAVIS_BUILD_DIR/conformance/protobuf/src:$PATH PROTO_PATH="-I. -I$TRAVIS_BUILD_DIR/conformance/protobuf/src" dub build :add_person
  - cd $TRAVIS_BUILD_DIR/examples && PATH=$TRAVIS_BUILD_DIR/conformance/protobuf/src:$PATH PROTO_PATH="-I. -I$TRAVIS_BUILD_DIR/conformance/protobuf/src" dub build :list_people
